name: Deploy Petljadoc site to Pages 

on:
  # Runs on pushes  targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    # URL to be shown whit a compleated workflow
    environment:
      name: github-pages
      url: ${{ steps.build.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish
        id: build
        uses: Petlja/petljadoc-action@main
